<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/yykim/TF_IDF_%EC%97%B0%EC%8A%B5(%ED%81%B4%EB%9E%98%EC%8A%A4%EA%B9%8C%EC%A7%80).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"

In [ ]:
#토크나이징
d1_token = d1.split(" ")
d2_token = d2.split(" ")

### TF 계산

In [ ]:
total_token = np.unique(d1_token + d2_token)
total_token

array(['I', 'The', 'a', 'bed', 'cat', 'dog', 'face', 'hate', 'love', 'my',
       'on', 'sat'], dtype='<U4')

In [ ]:
d1_token_count = []
for token in total_token:
    d1_token_count.append(d1_token.count(token))

d2_token_count = []
for token in total_token:
    d2_token_count.append(d2_token.count(token))

In [ ]:
print(total_token)

['I' 'The' 'a' 'bed' 'cat' 'dog' 'face' 'hate' 'love' 'my' 'on' 'sat']


In [ ]:
d1_token_count = np.array(d1_token_count)
d1_token_count

array([1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 1])

In [ ]:
#문서1의 토큰의 개수
len(d1_token)


10

In [ ]:
d1_tf=d1_token_count/len(d1_token)
d1_tf

array([0.1, 0.1, 0.1, 0. , 0.2, 0. , 0.1, 0.1, 0. , 0.1, 0.1, 0.1])

In [ ]:
d2_token_count = np.array(d2_token_count)
d2_token_count

array([1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1])

In [ ]:
#문서2의 토큰의 개수
len(d2_token)

10

In [ ]:
d2_tf=d2_token_count/len(d2_token)
d2_tf

array([0.1, 0.1, 0.1, 0.1, 0. , 0.2, 0. , 0. , 0.1, 0.1, 0.1, 0.1])

### IDF 계산

In [ ]:
d1_token_exist = [0 if i == 0 else 1 for i in d1_token_count]
d2_token_exist = [0 if i == 0 else 1 for i in d2_token_count]



In [ ]:
d1_token_exist = np.array(d1_token_exist)

In [ ]:
d2_token_exist = np.array(d2_token_exist)

In [ ]:
nt = d1_token_exist + d2_token_exist
nt

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2])

In [ ]:
nt*1/2

array([1. , 1. , 1. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. , 1. , 1. ])

In [ ]:
idf = np.log(2/nt)
idf

array([0.        , 0.        , 0.        , 0.69314718, 0.69314718,
       0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.        ,
       0.        , 0.        ])

In [ ]:
a_token = ['나는', '안녕']

nt = np.zeros((len(a_token),))
for i in tmp:
    nt += i
print(nt)
# idf = np.log(len(self.docs)/nt)


[0. 0.]


### TF-IDF 계산

In [ ]:
total_token

array(['I', 'The', 'a', 'bed', 'cat', 'dog', 'face', 'hate', 'love', 'my',
       'on', 'sat'], dtype='<U4')

In [ ]:
d1_tf*idf

array([0.        , 0.        , 0.        , 0.        , 0.13862944,
       0.        , 0.06931472, 0.06931472, 0.        , 0.        ,
       0.        , 0.        ])

In [ ]:
d2_tf*idf

array([0.        , 0.        , 0.        , 0.06931472, 0.        ,
       0.13862944, 0.        , 0.        , 0.06931472, 0.        ,
       0.        , 0.        ])

In [ ]:
final = pd.DataFrame(total_token)

In [ ]:
final['d1 TF-IDF'] = d1_tf*idf
final['d2 TF-IDF'] = d2_tf*idf

In [ ]:
final

0  d1 TF-IDF  d2 TF-IDF
0      I   0.000000   0.000000
1    The   0.000000   0.000000
2      a   0.000000   0.000000
3    bed   0.000000   0.069315
4    cat   0.138629   0.000000
5    dog   0.000000   0.138629
6   face   0.069315   0.000000
7   hate   0.069315   0.000000
8   love   0.000000   0.069315
9     my   0.000000   0.000000
10    on   0.000000   0.000000
11   sat   0.000000   0.000000

In [ ]:
final.rename({0:'토큰'},axis=1,inplace = True)

In [ ]:
final

토큰  d1 TF-IDF  d2 TF-IDF
0      I   0.000000   0.000000
1    The   0.000000   0.000000
2      a   0.000000   0.000000
3    bed   0.000000   0.069315
4    cat   0.138629   0.000000
5    dog   0.000000   0.138629
6   face   0.069315   0.000000
7   hate   0.069315   0.000000
8   love   0.000000   0.069315
9     my   0.000000   0.000000
10    on   0.000000   0.000000
11   sat   0.000000   0.000000

###함수로 만들기(일반화)
: 모듈화 하면 좋은점 순서 카오스 안되고 재사용 가능

In [ ]:
class TF_IDF:
    def __init__(self, a, docs): #a는 문장1개, docs는 bunch(리스트화 한거)
        self.a = a
        self.docs = docs
        self.total = []
        self.a_count = []
        self.a_token = []
        self.idf = 1
    
    def total_token(self):
        for doc in self.docs:
            doc_token = doc.split(" ")
            self.total.extend(doc_token)
        #전체 토큰의 개수 세기
        total_unique = np.unique(self.total)        
        return total_unique
    
    def count_token(self):
        #토크나이징
        self.a_token = self.a.split(" ")

        #해당 문서에 토큰 개수 세기 
        self.a_count = []
        for token in self.total:
            self.a_count.append(self.a_token.count(token))
        self.a_count = np.array([self.a_count])

        return self.a_count

    def get_tf(self):
        return self.a_count/len(self.a_token)

    def get_idf(self):
        tmp=[]
        for doc in self.docs: #문서 번치에서 문서 하나씩 빼냄
            doc_token = doc.split(" ") #문서 토크나이징
            doc_count = []  
            for token in self.total:
                doc_count.append(doc_token.count(token))           
            tmp.append(np.array([0 if i == 0 else 1 for i in doc_count]))

        nt = np.zeros((len(self.total),))
        for i in tmp:
            nt += i
        self.idf = np.log(len(self.docs)/nt)

        return self.idf

    def get_tf_idf(self):
        return self.a_count*self.idf       


In [ ]:
d1 = "나는 밥을 먹는다"
d2 = "나는 집에 간다"

bunch = [d1]+[d2]
bunch

['나는 밥을 먹는다', '나는 집에 간다']

In [ ]:
tfidf = TF_IDF(d1, bunch)

In [ ]:
print("토큰 목록: ",tfidf.total_token())
tfidf.count_token()
tfidf.get_tf()
tfidf.get_idf()
tfidf.get_tf_idf()

토큰 목록:  ['간다' '나는' '먹는다' '밥을' '집에']


array([[0.        , 0.69314718, 0.69314718, 0.        , 0.        ,
        0.        ]])

##sklearn 으로 해보기

In [ ]:
#TDM구하기
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"
corpus = [d1, d2]
count_vect = CountVectorizer()
countv = count_vect.fit_transform(corpus)
print(countv.toarray())
print(count_vect.vocabulary_)

[[0 2 0 1 1 0 1 1 1 1]
 [1 0 2 0 0 1 1 1 1 1]]
{'the': 9, 'cat': 1, 'sat': 8, 'on': 7, 'my': 6, 'face': 3, 'hate': 4, 'dog': 2, 'bed': 0, 'love': 5}


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"
corpus = [d1, d2]
tfidf_vect = TfidfVectorizer().fit(corpus)
tfidfv = tfidf_vect.transform(corpus)
print(tfidfv.toarray())
print(tfidf_vect.vocabulary_)

[[0.         0.70600557 0.         0.35300279 0.35300279 0.
  0.25116439 0.25116439 0.25116439 0.25116439]
 [0.35300279 0.         0.70600557 0.         0.         0.35300279
  0.25116439 0.25116439 0.25116439 0.25116439]]
{'the': 9, 'cat': 1, 'sat': 8, 'on': 7, 'my': 6, 'face': 3, 'hate': 4, 'dog': 2, 'bed': 0, 'love': 5}


## gensim 활용

In [ ]:
import gensim.downloader as api
from gensim.models import TfidfModel
from gensim import corpora

d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"
corpus = [d1, d2]

doc_ls = [doc.split() for doc in corpus]
id2word = corpora.Dictionary(doc_ls)  # fit dictionary (개별 단어들에 index 붙여주는 것)/dictionary형태로 들어감 ㅋㅋ
corpus = [id2word.doc2bow(doc) for doc in doc_ls]  # convert corpus to BoW format

tfidf = TfidfModel(corpus)  # fit model
vector = tfidf[corpus[0]]  # apply model to the first corpus document

In [ ]:
tfidf[corpus][0] #값이 있는 위치만 써줌 0은 넘김

[(3, 0.8164965809277261), (4, 0.4082482904638631), (5, 0.4082482904638631)]