<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/LSA_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [57]:
doc_is = ['바나나 사과 포도 포도 짜장면',
          '사과 포도',
          '포도 바나나',
          '짜장면 짬뽕 탕수육',
          '볶음밥 탕수육',
          '짜장면 짬뽕',
          '라면 스시',
          '스시 짜장면',
          '가츠동 스시 소바',
          '된장찌개 김치찌개 김치',
          '김치 된장 짜장면',
          '비빔밥 김치'
          ]

In [58]:

def tokenize(doc_is):
    doc_token = [doc.split() for doc in doc_is]
    
    return doc_token

doc_token =tokenize(doc_is)
doc_token

[['바나나', '사과', '포도', '포도', '짜장면'],
 ['사과', '포도'],
 ['포도', '바나나'],
 ['짜장면', '짬뽕', '탕수육'],
 ['볶음밥', '탕수육'],
 ['짜장면', '짬뽕'],
 ['라면', '스시'],
 ['스시', '짜장면'],
 ['가츠동', '스시', '소바'],
 ['된장찌개', '김치찌개', '김치'],
 ['김치', '된장', '짜장면'],
 ['비빔밥', '김치']]

In [59]:
from sklearn.feature_extraction.text import CountVectorizer

count_vec = CountVectorizer()
DTM = count_vec.fit_transform(doc_is)

tdm = DTM.toarray()







In [60]:
tdm

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [76]:
doc_names = ['문서'+ str(i+1) for i in range(len(doc_token))   ]
voca = count_vec.get_feature_names()

df_TDM = pd.DataFrame(DTM.toarray().T, columns=doc_names)
df_TDM['문서\단어'] = voca

tdmTable=df_TDM.set_index('문서\단어').T
tdmTable

문서\단어  가츠동  김치  김치찌개  된장  된장찌개  라면  바나나  볶음밥  비빔밥  사과  소바  스시  짜장면  짬뽕  탕수육  포도
문서1      0   0     0   0     0   0    1    0    0   1   0   0    1   0    0   2
문서2      0   0     0   0     0   0    0    0    0   1   0   0    0   0    0   1
문서3      0   0     0   0     0   0    1    0    0   0   0   0    0   0    0   1
문서4      0   0     0   0     0   0    0    0    0   0   0   0    1   1    1   0
문서5      0   0     0   0     0   0    0    1    0   0   0   0    0   0    1   0
문서6      0   0     0   0     0   0    0    0    0   0   0   0    1   1    0   0
문서7      0   0     0   0     0   1    0    0    0   0   0   1    0   0    0   0
문서8      0   0     0   0     0   0    0    0    0   0   0   1    1   0    0   0
문서9      1   0     0   0     0   0    0    0    0   0   1   1    0   0    0   0
문서10     0   1     1   0     1   0    0    0    0   0   0   0    0   0    0   0
문서11     0   1     0   1     0   0    0    0    0   0   0   0    1   0    0   0
문서12     0   1     0   0     0   0    0    0    1   0   0   0    0   0    0   0

#PCA

In [62]:
#표준화
from sklearn.preprocessing import StandardScaler
tdm_std = StandardScaler().fit_transform(tdm)

tdm_std

array([[-0.30151134, -0.57735027, -0.30151134, -0.30151134, -0.30151134,
        -0.30151134,  2.23606798, -0.30151134, -0.30151134,  2.23606798,
        -0.30151134, -0.57735027,  1.18321596, -0.4472136 , -0.4472136 ,
         2.67261242],
       [-0.30151134, -0.57735027, -0.30151134, -0.30151134, -0.30151134,
        -0.30151134, -0.4472136 , -0.30151134, -0.30151134,  2.23606798,
        -0.30151134, -0.57735027, -0.84515425, -0.4472136 , -0.4472136 ,
         1.06904497],
       [-0.30151134, -0.57735027, -0.30151134, -0.30151134, -0.30151134,
        -0.30151134,  2.23606798, -0.30151134, -0.30151134, -0.4472136 ,
        -0.30151134, -0.57735027, -0.84515425, -0.4472136 , -0.4472136 ,
         1.06904497],
       [-0.30151134, -0.57735027, -0.30151134, -0.30151134, -0.30151134,
        -0.30151134, -0.4472136 , -0.30151134, -0.30151134, -0.4472136 ,
        -0.30151134, -0.57735027,  1.18321596,  2.23606798,  2.23606798,
        -0.53452248],
       [-0.30151134, -0.57735027, -0

In [63]:
print(tdm_std.mean())
print(tdm_std.std())

-1.850371707708594e-17
1.0


In [ ]:
tdm_std

In [ ]:
tdm_std.T

In [ ]:
import numpy as np

# features are columns from x_std
features = tdm_std.T 
covariance_matrix = np.cov(features)



print(covariance_matrix)

In [ ]:
eig_vals, eig_vecs = np.linalg.eig(covariance_matrix)
print('Eigenvalues \n%s' %eig_vals)
print('Eigenvectors \n%s' %eig_vecs)

#SVD

In [79]:
A= tdm
A

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
import numpy as np

# SVD
U, s, VT = np.linalg.svd(A)

print("U:\n {}".format(U))
print("s:\n {}".format(s))
print("VT:\n {}".format(VT))

In [ ]:
U[:,:4]
s[:4]
VT[:4,:]

In [ ]:
voca

In [106]:
def _model_topic(A, n_topics, n_words): #행렬A에서 n_topics개의 토픽 추출, 토픽당 n_words개의 단어를 추출
    U, s, VT = np.linalg.svd(A)
    for topic in range(n_topics) :
        sort = np.argsort(VT.T[:,topic])[::-1]
        top = sort[0:n_words]

        words_group = []
        for i in top :
            words_group.append((voca[i],  '%.3f' %VT.T[:,topic][i]))
        print("Topic{}: {}".format(topic+1, words_group))
        
_model_topic(A, 4, 3)


Topic1: [('포도', '0.697'), ('짜장면', '0.486'), ('사과', '0.348')]
Topic2: [('포도', '0.387'), ('사과', '0.194'), ('바나나', '0.194')]
Topic3: [('스시', '0.523'), ('소바', '0.226'), ('가츠동', '0.226')]
Topic4: [('스시', '0.552'), ('김치', '0.371'), ('소바', '0.277')]
