<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/jisang/12_Latent_Semantic_Analysis_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic Modeling - Latent Semantic Analysis 실습**

## **1-1. 잠재 의미 분석(LSA)**

In [7]:
doc_ls = ['바나나 사과 포도 포도 짜장면',
          '사과 포도',
          '포도 바나나',
          '짜장면 짬뽕 탕수육',
          '볶음밥 탕수육',
          '짜장면 짬뽕',
          '라면 스시',
          '스시 짜장면',
          '가츠동 스시 소바',
          '된장찌개 김치찌개 김치',
          '김치 된장 짜장면',          
          '비빔밥 김치'
          ]

In [8]:
# 각 문장 토큰화
docs = []
tokens = []

for i in range(len(doc_ls)):
    docs.append(doc_ls[i].split(" "))
    # 단어 뭉치 생성
    for word in docs[i]:
        tokens.append(word)
tokens = list(set(tokens))

docs, tokens

([['바나나', '사과', '포도', '포도', '짜장면'],
  ['사과', '포도'],
  ['포도', '바나나'],
  ['짜장면', '짬뽕', '탕수육'],
  ['볶음밥', '탕수육'],
  ['짜장면', '짬뽕'],
  ['라면', '스시'],
  ['스시', '짜장면'],
  ['가츠동', '스시', '소바'],
  ['된장찌개', '김치찌개', '김치'],
  ['김치', '된장', '짜장면'],
  ['비빔밥', '김치']],
 ['김치',
  '탕수육',
  '가츠동',
  '김치찌개',
  '볶음밥',
  '짜장면',
  '사과',
  '된장찌개',
  '비빔밥',
  '스시',
  '포도',
  '바나나',
  '짬뽕',
  '소바',
  '라면',
  '된장'])

In [9]:
import pandas as pd

# TDM(문서-단어 행렬) 생성
TDM_matrix = []

for i in range(len(docs)):
    words_count = [0 for a in range(len(tokens))]
    for j in range(len(tokens)):
        if tokens[j] in docs[i]:
            words_count[j] += docs[i].count(tokens[j])
    TDM_matrix.append(words_count)

df = pd.DataFrame(TDM_matrix, index=doc_ls,  columns=tokens)
df

김치  탕수육  가츠동  김치찌개  볶음밥  짜장면  사과  ...  스시  포도  바나나  짬뽕  소바  라면  된장
바나나 사과 포도 포도 짜장면   0    0    0     0    0    1   1  ...   0   2    1   0   0   0   0
사과 포도              0    0    0     0    0    0   1  ...   0   1    0   0   0   0   0
포도 바나나             0    0    0     0    0    0   0  ...   0   1    1   0   0   0   0
짜장면 짬뽕 탕수육         0    1    0     0    0    1   0  ...   0   0    0   1   0   0   0
볶음밥 탕수육            0    1    0     0    1    0   0  ...   0   0    0   0   0   0   0
짜장면 짬뽕             0    0    0     0    0    1   0  ...   0   0    0   1   0   0   0
라면 스시              0    0    0     0    0    0   0  ...   1   0    0   0   0   1   0
스시 짜장면             0    0    0     0    0    1   0  ...   1   0    0   0   0   0   0
가츠동 스시 소바          0    0    1     0    0    0   0  ...   1   0    0   0   1   0   0
된장찌개 김치찌개 김치       1    0    0     1    0    0   0  ...   0   0    0   0   0   0   0
김치 된장 짜장면          1    0    0     0    0    1   0  ...   0   0    0   0   0   0   1
비빔밥 김치             1    0    0     0    0    0   0  ...   0   0    0   0   0   0   0

[12 rows x 16 columns]

In [10]:
import numpy as np

# 특이값 분해(SVD, Singular Value Decomposition)
U, s, VT = np.linalg.svd(TDM_matrix)

print("U:\n {}".format(U))
print("s:\n {}".format(s))
print("VT:\n {}".format(VT))

U:
 [[ 7.99091783e-01  2.36316994e-01 -1.00528910e-02  1.86641353e-02
   2.26958130e-02 -1.49376350e-03 -2.77279457e-03 -3.68544915e-02
   1.13558993e-16 -1.17652823e-01 -2.96599016e-02  5.37170383e-01]
 [ 3.24228913e-01  2.37554400e-01 -2.30122874e-02  5.61972271e-02
  -9.68984211e-02  3.15314058e-03  5.42121261e-03  5.97770914e-02
  -7.07106781e-01  1.44987002e-01  3.17878330e-02 -5.47468895e-01]
 [ 3.24228913e-01  2.37554400e-01 -2.30122874e-02  5.61972271e-02
  -9.68984211e-02  3.15314058e-03  5.42121261e-03  5.97770914e-02
   7.07106781e-01  1.44987002e-01  3.17878330e-02 -5.47468895e-01]
 [ 2.12081980e-01 -4.85658930e-01  1.28131746e-01 -4.30050644e-01
  -2.29550714e-01 -1.49219512e-01  7.74475499e-02  2.17717819e-01
  -5.55111512e-17  1.91835325e-01  5.93643666e-01  1.49190202e-02]
 [ 2.52665818e-02 -1.21890924e-01  5.54551687e-02 -2.15417887e-01
  -7.72035525e-01  3.54259781e-01 -1.44920552e-01 -2.56260382e-01
  -1.38777878e-16 -1.33737715e-01 -3.29953280e-01 -7.67610447e-03]
 

In [13]:
# 주제 개수 설정
k = 4

# 주제-단어 행렬
VT_matrix = VT.T[:, :k]
columns_name = ["Topic {}".format(i+1) for i in range(k)]
df = pd.DataFrame(VT_matrix, index=tokens, columns=columns_name)

# 단어 순위 설정
word_num = 3

# 순위 출력 결과
topic_result = []
for name in columns_name:
    topic_top = df[name].sort_values(ascending=False)[0:word_num]
    topic_result.append(([topic_top.index, topic_top.values]))

topic_result

[[Index(['포도', '짜장면', '사과'], dtype='object'),
  array([0.69686254, 0.48563449, 0.34843127])],
 [Index(['포도', '사과', '바나나'], dtype='object'),
  array([0.38741921, 0.19370961, 0.19370961])],
 [Index(['스시', '소바', '가츠동'], dtype='object'),
  array([0.52268348, 0.22621639, 0.22621639])],
 [Index(['스시', '김치', '가츠동'], dtype='object'),
  array([0.55238845, 0.37136542, 0.27669846])]]

In [14]:
# 최종 결과
result = []

for i in range(len(topic_result)):
    tmp_result = []
    for j in range(word_num):
        tmp_result.append((topic_result[i][0][j], topic_result[i][1][j]))
    result.append(tmp_result)

result

[[('포도', 0.6968625387988912),
  ('짜장면', 0.4856344888220903),
  ('사과', 0.3484312693994456)],
 [('포도', 0.3874192129673672),
  ('사과', 0.19370960648368363),
  ('바나나', 0.19370960648368346)],
 [('스시', 0.522683479087483),
  ('소바', 0.2262163850882104),
  ('가츠동', 0.22621638508821038)],
 [('스시', 0.5523884496346702),
  ('김치', 0.37136541740506135),
  ('가츠동', 0.2766984641841536)]]

In [15]:
for i in range(len(result)):
    print("{} - {}".format(columns_name[i], result[i]))

Topic 1 - [('포도', 0.6968625387988912), ('짜장면', 0.4856344888220903), ('사과', 0.3484312693994456)]
Topic 2 - [('포도', 0.3874192129673672), ('사과', 0.19370960648368363), ('바나나', 0.19370960648368346)]
Topic 3 - [('스시', 0.522683479087483), ('소바', 0.2262163850882104), ('가츠동', 0.22621638508821038)]
Topic 4 - [('스시', 0.5523884496346702), ('김치', 0.37136541740506135), ('가츠동', 0.2766984641841536)]
