<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/jyp/skip_gram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
class skip_gram:
    def __init__(self,token_ls):
        self.token_ls=token_ls
        self.word_ls=sorted(list(set(self.token_ls)))

    def connected_token(self,token,window_size):
        token_index_ls=[i for i,v in enumerate(self.token_ls) if v==token]
        return_set={self.word_ls.index(v) for i,v in enumerate(self.token_ls) for j in token_index_ls if abs(i-j)<=window_size}-{self.word_ls.index(token)}
        return sorted(list(return_set))

    

In [3]:
L=["딸기","바나나","사과","딸기","파인애플","포도","블루베리"]
print(sorted(skip_gram(L).word_ls))
skip_gram(L).connected_token("딸기",2)

['딸기', '바나나', '블루베리', '사과', '파인애플', '포도']


[1, 3, 4, 5]

In [6]:
X=[[np.identity(n)[i] for j in skip_gram(L).connected_token(skip_gram(L).word_ls[i],2)] for i in range(n)]
X=sum(X,[])
y=[[np.identity(n)[j] for j in skip_gram(L).connected_token(skip_gram(L).word_ls[i],2)] for i in range(n)]
y=sum(y,[])
X,y=np.array(X),np.array(y)

In [7]:
X_1=np.column_stack((np.ones(len(X)),X))
X_1

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.]])

In [10]:
learning_rate=0.001
num_epoch=100000
np.random.seed(0)
n=len(skip_gram(L).word_ls)
hidden_num=3
W_1=np.random.random(size=(n+1,hidden_num))
W_2=np.random.random(size=(hidden_num+1,n))
for i in range(num_epoch):
    first_layer=np.dot(X_1,W_1)
    output_layer=np.dot(np.column_stack((np.ones(len(first_layer)),first_layer)),W_2)
    hyp=(np.exp(output_layer).T/np.exp(output_layer).sum(axis=1)).T
    error=-np.multiply(y,np.log(hyp)).sum()/len(X)
    hyp.argmax()

    if error<0.12:
        break
    W_1=W_1-np.dot(np.dot(hyp-y,W_2.T).T[1:],X_1).T*learning_rate/len(X)
    W_2=W_2-np.dot(np.column_stack((np.ones(len(first_layer)),first_layer)).T,(hyp-y))*learning_rate/len(X)
print(error)

1.2464389525882285


In [11]:
y

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [12]:
hyp

array([[1.39434120e-02, 1.85130540e-01, 2.92007304e-02, 1.45485091e-01,
        3.11884786e-01, 3.14355440e-01],
       [1.39434120e-02, 1.85130540e-01, 2.92007304e-02, 1.45485091e-01,
        3.11884786e-01, 3.14355440e-01],
       [1.39434120e-02, 1.85130540e-01, 2.92007304e-02, 1.45485091e-01,
        3.11884786e-01, 3.14355440e-01],
       [1.39434120e-02, 1.85130540e-01, 2.92007304e-02, 1.45485091e-01,
        3.11884786e-01, 3.14355440e-01],
       [4.26875266e-01, 2.06903300e-04, 1.04552736e-01, 4.34165469e-01,
        9.05482223e-03, 2.51448040e-02],
       [4.26875266e-01, 2.06903300e-04, 1.04552736e-01, 4.34165469e-01,
        9.05482223e-03, 2.51448040e-02],
       [2.15342416e-04, 4.83864558e-02, 8.43539383e-04, 9.10096948e-02,
        4.36877591e-01, 4.22667376e-01],
       [2.15342416e-04, 4.83864558e-02, 8.43539383e-04, 9.10096948e-02,
        4.36877591e-01, 4.22667376e-01],
       [2.57082833e-01, 2.97820861e-01, 8.92490970e-02, 2.70598616e-03,
        3.52889624e-01, 

In [ ]:
import tensorflow 
from tensorflow.keras import layers,models,Sequential
model=Sequential([
                 layers.Dense(3,input_shape=(n,),activation='linear'),
                 layers.Dense(n,activation='softmax')
                 ])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X,y,epochs=20)