<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/jyp/skip_gram_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class skip_gram:
    def __init__(self,token_ls):
        self.token_ls=token_ls
        self.word_ls=sorted(list(set(self.token_ls)))

    def connected_token(self,token,window_size):
        token_index_ls=[i for i,v in enumerate(self.token_ls) if v==token]
        return_set={self.word_ls.index(v) for i,v in enumerate(self.token_ls) for j in token_index_ls if abs(i-j)<=window_size}-{self.word_ls.index(token)}
        return sorted(list(return_set))

    

In [ ]:
L=["딸기","바나나","사과","딸기","파인애플","포도","블루베리"]
print(sorted(skip_gram(L).word_ls))
skip_gram(L).connected_token("딸기",2)

['딸기', '바나나', '블루베리', '사과', '파인애플', '포도']


[1, 3, 4, 5]

In [ ]:
n=len(skip_gram(L).word_ls)
X=[[np.identity(n)[i] for j in skip_gram(L).connected_token(skip_gram(L).word_ls[i],2)] for i in range(n)]
X=sum(X,[])
y=[[np.identity(n)[j] for j in skip_gram(L).connected_token(skip_gram(L).word_ls[i],2)] for i in range(n)]
y=sum(y,[])
X,y=np.array(X),np.array(y)
X_1=np.column_stack((np.ones(len(X)),X))

In [ ]:
learning_rate=0.003
num_epoch=400000
np.random.seed(0)
hidden_num=5

W_1=np.random.random(size=(n+1,hidden_num))
W_2=np.random.random(size=(hidden_num+1,n))

for epoch in range(num_epoch):
    first_layer=np.dot(X_1,W_1)
    output_layer=np.dot(np.column_stack((np.ones(len(first_layer)),first_layer)),W_2)
    hyp=(np.exp(output_layer).T/np.exp(output_layer).sum(axis=1)).T
    error=-np.multiply(y,np.log(hyp)).sum()/len(X)
    
    len_neighbor=[len(skip_gram(L).connected_token(skip_gram(L).word_ls[j],2)) for j in range(n)]
    arr=np.zeros(n)
    for p,v in enumerate(np.argsort(-hyp)[[sum(len_neighbor[:j]) for j in range(n)]]):
        arr=np.row_stack((arr,np.identity(n)[v<len_neighbor[p]]))
    pred=arr[1:]
    accuracy=(y.argmax(axis=1)==pred.argmax(axis=1)).mean()
    if epoch%50000==0:
        print(f"epoch : {epoch} accuracy : {accuracy}")
    if accuracy>0.9:
        break
    W_1=W_1-np.dot(X_1.T,np.dot(hyp-y,W_2.T).T[1:].T)*learning_rate/len(X)
    W_2=W_2-np.dot(np.column_stack((np.ones(len(first_layer)),first_layer)).T,(hyp-y))*learning_rate/len(X)
print(f"epoch : {epoch} accuracy : {accuracy}")

epoch : 0 accuracy : 0.2777777777777778
epoch : 50000 accuracy : 0.6666666666666666
epoch : 100000 accuracy : 0.6666666666666666
epoch : 150000 accuracy : 0.6666666666666666
epoch : 200000 accuracy : 0.6666666666666666
epoch : 250000 accuracy : 0.6666666666666666
epoch : 300000 accuracy : 0.6666666666666666
epoch : 350000 accuracy : 0.6666666666666666
epoch : 399999 accuracy : 0.6666666666666666


In [ ]:
y==pred

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [ True,  True,  True, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
hyp

array([[5.79751023e-05, 2.49982579e-01, 2.69608210e-06, 2.49954897e-01,
        2.49980913e-01, 2.50020940e-01],
       [5.79751023e-05, 2.49982579e-01, 2.69608210e-06, 2.49954897e-01,
        2.49980913e-01, 2.50020940e-01],
       [5.79751023e-05, 2.49982579e-01, 2.69608210e-06, 2.49954897e-01,
        2.49980913e-01, 2.50020940e-01],
       [5.79751023e-05, 2.49982579e-01, 2.69608210e-06, 2.49954897e-01,
        2.49980913e-01, 2.50020940e-01],
       [4.99939245e-01, 6.65161945e-05, 5.14809007e-05, 4.99901163e-01,
        6.18045423e-07, 4.09767322e-05],
       [4.99939245e-01, 6.65161945e-05, 5.14809007e-05, 4.99901163e-01,
        6.18045423e-07, 4.09767322e-05],
       [6.11379375e-07, 4.63039099e-05, 6.52942722e-05, 4.23956089e-05,
        4.99946121e-01, 4.99899274e-01],
       [6.11379375e-07, 4.63039099e-05, 6.52942722e-05, 4.23956089e-05,
        4.99946121e-01, 4.99899274e-01],
       [3.33281329e-01, 3.33267667e-01, 3.57556519e-05, 6.47736640e-05,
        3.33349495e-01, 

In [ ]:
np.identity(n)(hyp>1/n)

TypeError: ignored

In [ ]:
hyp>1/n

array([[False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [ True,  True, False, False,  True, False],
       [ True,  True, False, False,  True, False],
       [ True,  True, False, False,  True, False],
       [ True, False,  True,  True, False,  True],
       [ True, False,  True,  True, False,  True],
       [ True, False,  True,  True, False,  True],
       [ True, False,  True,  True, False,  True],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [ ]:
np.row_stack(np.zeros(n),np.ones(n))

TypeError: ignored

In [ ]:
np.argsort(-hyp)[[sum(len_neighbor[:i]) for i in range(n)]][0]<=len_neighbor[0]

array([ True, False,  True,  True,  True,  True])

In [ ]:
len_neighbor=[len(skip_gram(L).connected_token(skip_gram(L).word_ls[i],2)) for i in range(n)]
arr=np.zeros(n)
for p,v in enumerate(np.argsort(-hyp)[[sum(len_neighbor[:i]) for i in range(n)]]):
    arr=np.row_stack((arr,np.identity(n)[v<len_neighbor[p]]))
pred=arr[1:]
(y.argmax(axis=1)==pred.argmax(axis=1)).mean()

0.5555555555555556

In [ ]:
import tensorflow 
from tensorflow.keras import layers,models,Sequential
model=Sequential([
                 layers.Dense(3,input_shape=(n,),activation='linear'),
                 layers.Dense(n,activation='softmax')
                 ])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X,y,epochs=20)