<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/Sojeong_Cho/20200717_%EB%AC%B8%EC%84%9C%EC%9A%94%EC%95%BD_Textrank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
nodes = "딸기 바나나 사과 파인애플 수박. 바나나 사과 딸기 포도. 복숭아 수박. 파인애플 사과 딸기 바나나."

In [36]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
import numpy as np
import math
import networkx as nx
# d1 = [d.split(".")]
# d1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [48]:
tokens = sent_tokenize(nodes)
tokens_t = np.array(tokens)
print(tokens_t)

token_1 = tokens_t[0].replace(".","")
print(token_1)
token_2 = tokens_t[1].replace(".","")
print(tokens_2)
token_3 = tokens_t[2].replace(".","")
print(token_3)
token_4 = tokens_t[3].replace(".","")
print(token_4)

['딸기 바나나 사과 파인애플 수박.' '바나나 사과 딸기 포도.' '복숭아 수박.' '파인애플 사과 딸기 바나나.']
딸기 바나나 사과 파인애플 수박
바나나 사과 딸기 포도.
복숭아 수박
파인애플 사과 딸기 바나나


In [86]:
token_s1 = token_1.split()
print(token_s1)
token_s2 = token_2.split()
print(token_s2)
token_s3 = token_3.split()
print(token_s3)
token_s4 = token_4.split()
print(token_s4)

doc = []

doc.append(token_s1)
doc.append(token_s2)
doc.append(token_s3)
doc.append(token_s4)

doc1 = np.array(doc)
doc1

['딸기', '바나나', '사과', '파인애플', '수박']
['바나나', '사과', '딸기', '포도']
['복숭아', '수박']
['파인애플', '사과', '딸기', '바나나']


array([list(['딸기', '바나나', '사과', '파인애플', '수박']),
       list(['바나나', '사과', '딸기', '포도']), list(['복숭아', '수박']),
       list(['파인애플', '사과', '딸기', '바나나'])], dtype=object)

In [141]:
# 문장간 유사도

def Jaccard(t, d):
    union = set(t).union(set(d))
    intersection = set(t).intersection(set(d))
    return len(intersection)/len(union)

S = {}  
for i in range(len(doc1)):
    for j in range(len(doc1)):
        S.setdefault((i,j),Jaccard(doc[i], doc[j]))
S

#         graph_edge[i][j] = temp_sum/len(list(count_vectorizer.vocabulary_.keys()))
# graph_edge

{(0, 0): 1.0,
 (0, 1): 0.5,
 (0, 2): 0.16666666666666666,
 (0, 3): 0.8,
 (1, 0): 0.5,
 (1, 1): 1.0,
 (1, 2): 0.0,
 (1, 3): 0.6,
 (2, 0): 0.16666666666666666,
 (2, 1): 0.0,
 (2, 2): 1.0,
 (2, 3): 0.0,
 (3, 0): 0.8,
 (3, 1): 0.6,
 (3, 2): 0.0,
 (3, 3): 1.0}

In [125]:
del S[4]
S

[0.5, 0.16666666666666666, 0.8, 0.6]

In [128]:
print(S)

[0.5, 0.16666666666666666, 0.8, 0.6]


In [199]:
G_1 = np.zeros((4,4))
print(G_1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [200]:
for i in S:
    G_1[i] = S[i]
for i in range(len(graph)):
    G_1[(i,i)] = 0

In [201]:
print(G_1)

[[0.         0.5        0.16666667 0.8       ]
 [0.5        0.         0.         0.6       ]
 [0.16666667 0.         0.         0.        ]
 [0.8        0.6        0.         0.        ]]


In [202]:
# 엣지 가중치

G_2 = np.array(G_1)
G_2

array([[0.        , 0.5       , 0.16666667, 0.8       ],
       [0.5       , 0.        , 0.        , 0.6       ],
       [0.16666667, 0.        , 0.        , 0.        ],
       [0.8       , 0.6       , 0.        , 0.        ]])

In [203]:
E_W = []

for i in G_2:
    E_W.append(list(i/sum(i)))

print(E_W)

[[0.0, 0.3409090909090909, 0.11363636363636362, 0.5454545454545454], [0.45454545454545453, 0.0, 0.0, 0.5454545454545454], [1.0, 0.0, 0.0, 0.0], [0.5714285714285715, 0.4285714285714286, 0.0, 0.0]]


In [204]:
E_W_2 = np.transpose(E_W)
E_W_2

array([[0.        , 0.45454545, 1.        , 0.57142857],
       [0.34090909, 0.        , 0.        , 0.42857143],
       [0.11363636, 0.        , 0.        , 0.        ],
       [0.54545455, 0.54545455, 0.        , 0.        ]])

In [192]:
D_F = 0.85

# for i in E_W:
#     (1-D_F)+D_F*(np.sum(i, axis=0))
scores = np.zeros(4,)

for p in range(30) : 
    for j, e in enumerate(E_W_2):
        for i, z in enumerate(E_W_2):
            scores[i] = (1-D_F)+D_F*(np.sum(i))
            E_W_2[(i, j)] = E_W_2[(i, j)]*scores[i]

    print(scores)


# sen_1 = (1-D_F)+D_F*(np.sum(E_W, axis=0))
# sen_1

[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]
[0.15 1.   1.85 2.7 ]


In [ ]:
scores=make_scores(graph)

for iter in range(10):    # 10번 반복
    for i, v in enumerate(graph):
        for j,w in enumerate(graph):
            graph[(i,j)] = edge_weight[(i,j)]*scores[i]
    scores = make_scores(graph)              
    print(graph)
    print(scores)
    print("="*50)

In [205]:
E_W_2

array([[0.        , 0.45454545, 1.        , 0.57142857],
       [0.34090909, 0.        , 0.        , 0.42857143],
       [0.11363636, 0.        , 0.        , 0.        ],
       [0.54545455, 0.54545455, 0.        , 0.        ]])

In [210]:
scores = np.zeros(4, )

scores_total = []

for j, e in enumerate(E_W_2):
    score = ((1-D_F)+D_F*(np.sum(e)))
    for z, q in enumerate():

TypeError: ignored

In [208]:
D_F = 0.85

# for i in E_W:
#     (1-D_F)+D_F*(np.sum(i, axis=0))
scores = np.zeros(4,)

# for p in range(30) : 
for j, e in enumerate(E_W_2):
    score = ((1-D_F)+D_F*(np.sum(e)))

for i, z in enumerate(E_W_2):
    E_W_2[(i,j)] = E_W_2[(i,j)]*score[j]


    #         E_W_2[(i, j)] = E_W_2[(i, j)]*scores[i]

    #     scores[j] = (1-D_F)+D_F*(np.sum(i))

    # print(scores)


# sen_1 = (1-D_F)+D_F*(np.sum(E_W, axis=0))
# sen_1

1.8720779220779225
0.8040584415584415
0.24659090909090908
1.0772727272727272


=== 핵심문장키워드 ===


[('바나나 사과 딸기 포도.', 0.1895178251747502),
 ('복숭아 수박.', 0.1895178251747502),
 ('딸기 바나나 사과 파인애플 수박.', 0.10244269200706907),
 ('파인애플 사과 딸기 바나나.', 0.10244269200706907)]

{'나', '포', '바', '기', '수', '딸', ' ', '과', '숭', '아', '복', '사', '박', '도'}
{' '}
0.07142857142857142
