<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/Sojeong_Cho/TextRank_%EB%AC%B8%EC%84%9C%EC%9A%94%EC%95%BD_%EC%A1%B0%EC%86%8C%EC%A0%95_%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TextRank: 문서요약

In [79]:
nodes = "딸기 바나나 사과 파인애플 수박. 바나나 사과 딸기 포도. 복숭아 수박. 파인애플 사과 딸기 바나나."

In [80]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
import numpy as np
import math
import networkx as nx

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [81]:
# 토큰화
tokens = sent_tokenize(nodes)
tokens_t = np.array(tokens)
print(tokens_t)

token_1 = tokens_t[0].replace(".","")
print(token_1)
token_2 = tokens_t[1].replace(".","")
print(token_2)
token_3 = tokens_t[2].replace(".","")
print(token_3)
token_4 = tokens_t[3].replace(".","")
print(token_4)

['딸기 바나나 사과 파인애플 수박.' '바나나 사과 딸기 포도.' '복숭아 수박.' '파인애플 사과 딸기 바나나.']
딸기 바나나 사과 파인애플 수박
바나나 사과 딸기 포도
복숭아 수박
파인애플 사과 딸기 바나나


In [82]:
token_s1 = token_1.split()
print(token_s1)
token_s2 = token_2.split()
print(token_s2)
token_s3 = token_3.split()
print(token_s3)
token_s4 = token_4.split()
print(token_s4)

doc = []

doc.append(token_s1)
doc.append(token_s2)
doc.append(token_s3)
doc.append(token_s4)

doc1 = np.array(doc)
doc1

['딸기', '바나나', '사과', '파인애플', '수박']
['바나나', '사과', '딸기', '포도']
['복숭아', '수박']
['파인애플', '사과', '딸기', '바나나']


array([list(['딸기', '바나나', '사과', '파인애플', '수박']),
       list(['바나나', '사과', '딸기', '포도']), list(['복숭아', '수박']),
       list(['파인애플', '사과', '딸기', '바나나'])], dtype=object)

In [83]:
# 문장간 유사도

def Jaccard(t, d):
    union = set(t).union(set(d))
    intersection = set(t).intersection(set(d))
    return len(intersection)/len(union)

S = {}  
for i in range(len(doc1)):
    for j in range(len(doc1)):
        S.setdefault((i,j),Jaccard(doc[i], doc[j]))
S

{(0, 0): 1.0,
 (0, 1): 0.5,
 (0, 2): 0.16666666666666666,
 (0, 3): 0.8,
 (1, 0): 0.5,
 (1, 1): 1.0,
 (1, 2): 0.0,
 (1, 3): 0.6,
 (2, 0): 0.16666666666666666,
 (2, 1): 0.0,
 (2, 2): 1.0,
 (2, 3): 0.0,
 (3, 0): 0.8,
 (3, 1): 0.6,
 (3, 2): 0.0,
 (3, 3): 1.0}

In [84]:
G_1 = np.zeros((4,4))
print(G_1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [85]:
for i in S:
    G_1[i] = S[i]
for i in range(len(G_1)):
    G_1[(i,i)] = 0

In [86]:
print(G_1)

[[0.         0.5        0.16666667 0.8       ]
 [0.5        0.         0.         0.6       ]
 [0.16666667 0.         0.         0.        ]
 [0.8        0.6        0.         0.        ]]


In [87]:
G_2 = np.array(G_1)
G_2

array([[0.        , 0.5       , 0.16666667, 0.8       ],
       [0.5       , 0.        , 0.        , 0.6       ],
       [0.16666667, 0.        , 0.        , 0.        ],
       [0.8       , 0.6       , 0.        , 0.        ]])

In [88]:
# 엣지 가중치

E_W = []

for i in G_2:
    E_W.append(list(i/sum(i)))

print(E_W)

[[0.0, 0.3409090909090909, 0.11363636363636362, 0.5454545454545454], [0.45454545454545453, 0.0, 0.0, 0.5454545454545454], [1.0, 0.0, 0.0, 0.0], [0.5714285714285715, 0.4285714285714286, 0.0, 0.0]]


In [89]:
E_W_2 = np.transpose(E_W)
print(E_W_2)

[[0.         0.45454545 1.         0.57142857]
 [0.34090909 0.         0.         0.42857143]
 [0.11363636 0.         0.         0.        ]
 [0.54545455 0.54545455 0.         0.        ]]


In [90]:
#for i in range(len(E_W_2)) :
#    E_W_2[i] = E_W_2[i] / np.sum(E_W_2[i], axis=0)

In [91]:
#E_W_2

In [92]:
# 반복

D_F = 0.85
MAX_ITER = 10
score = np.ones(len(E_W_2))
tmp = np.copy(G_2)
print(score)
for i in range(MAX_ITER) :
    for t, e in enumerate(tmp):
        score[t] = (1-D_F)+D_F*(np.sum(e))
        #print(e)
        #print(np.sum(e))
        #print(score[t])
    print(score)

    for j in range(len(score)) : 
        tmp[j] = score[j] * E_W_2.T[j]
        #print(score[j])
        #print(E_W_2[j])
        #print(tmp[j])
    tmp = tmp.T #머리 식힌뒤에 다시 고민해보겠습니다.

    print(np.sum(e))
    print('----')

[1. 1. 1. 1.]
[1.39666667 1.085      0.29166667 1.34      ]
1.34
----
[1.46797835 1.04285877 0.2849053  1.30059091]
1.3005909090909094
----
[1.4268078  1.04916678 0.29179336 1.31411539]
1.3141153925619835
----
[1.44166887 1.04216345 0.28781666 1.29795185]
1.297951849307717
----
[1.42773198 1.04058164 0.28925211 1.30159499]
1.3015949855632605
----
[1.43011047 1.03787025 0.28790593 1.29439995]
1.2943999492089502
----
[1.42442391 1.03593842 0.28813567 1.29424561]
1.2942456079791858
----
[1.42379784 1.03423439 0.2875864  1.29071345]
1.290713445271274
----
[1.42095696 1.03276625 0.28752593 1.28963312]
1.289633122178437
----
[1.41981359 1.0315495  0.28725152 1.28763531]
1.287635306391198
----
