<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/Sojeong_Cho/TF_IDF_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"

In [ ]:
docs = [d1, d2]

In [ ]:
d_N = len(docs)
d_N

2

In [ ]:
d1_token = d1.split(" ")
d2_token = d2.split(" ")
print(d1_token)
print(d2_token)

['The', 'cat', 'sat', 'on', 'my', 'face', 'I', 'hate', 'a', 'cat']
['The', 'dog', 'sat', 'on', 'my', 'bed', 'I', 'love', 'a', 'dog']


In [ ]:
word_list = np.unique(d1_token + d2_token)
word_list

array(['I', 'The', 'a', 'bed', 'cat', 'dog', 'face', 'hate', 'love', 'my',
       'on', 'sat'], dtype='<U4')

In [ ]:
d1_count=[]
for word in word_list:
    d1_count.append(d1_token.count(word))

d1_count

[1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 1]

In [ ]:
d1_len = len(d1_token)
d1_len

10

In [ ]:
d1_TF = []

for i in d1_count:
    a = i/d1_len
    d1_TF.append(a)

print(d1_TF)

# val = d1_count[0]
# val1 = (val/d1_len)
# print(val1)

[0.1, 0.1, 0.1, 0.0, 0.2, 0.0, 0.1, 0.1, 0.0, 0.1, 0.1, 0.1]


In [ ]:
d2_count=[]
for word in word_list:
    d2_count.append(d2_token.count(word))

d2_count

[1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1]

In [ ]:
d2_len = len(d2_token)
d2_len

10

In [ ]:
d2_TF = []

for z in d2_count:
    a = z/d2_len
    d2_TF.append(a)

print(d2_TF)

[0.1, 0.1, 0.1, 0.1, 0.0, 0.2, 0.0, 0.0, 0.1, 0.1, 0.1, 0.1]


In [ ]:
docs = [d1, d2]
docs

['The cat sat on my face I hate a cat', 'The dog sat on my bed I love a dog']

In [ ]:
d_N = len(docs)
d_N

2

In [ ]:
word_list = np.unique(d1_token + d2_token)
word_list

array(['I', 'The', 'a', 'bed', 'cat', 'dog', 'face', 'hate', 'love', 'my',
       'on', 'sat'], dtype='<U4')

In [ ]:
dn1_count = []

for e in d1_count:
    if e != 0:
        print(e)
        e=1
    else:
        print(0)
    dn1_count.append(e)

print(dn1_count)

1
1
1
0
2
0
1
1
0
1
1
1
[1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [ ]:
dn2_count = []

for r in d2_count:
    if r != 0:
        print(r)
        r=1
    else:
        print(0)
    dn2_count.append(r)

print(dn2_count)

1
1
1
1
0
2
0
0
1
1
1
1
[1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1]


In [ ]:
dn1_result = np.array(dn1_count)
dn1_result

array([1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1])

In [ ]:
dn2_result = np.array(dn2_count)
dn2_result

array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

In [ ]:
dn_result = dn1_result + dn2_result
dn_result # 토큰이 등장한 문서수

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2])

In [ ]:
d_N_array = np.array(d_N)
d_N_array

array(2)

In [ ]:
from numpy import log as ln

In [ ]:
IDF = []

for t in dn_result:
    a = ln(d_N_array/t)
    IDF.append(a)

print(IDF)

[0.0, 0.0, 0.0, 0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.0, 0.0, 0.0]


In [ ]:
#np.ln - 로그

In [ ]:
# TF-IDF 계산

In [ ]:
d1_TF1 = np.array(d1_TF)
d1_TF1

array([0.1, 0.1, 0.1, 0. , 0.2, 0. , 0.1, 0.1, 0. , 0.1, 0.1, 0.1])

In [ ]:
IDF1 = np.array(IDF)
IDF1

array([0.        , 0.        , 0.        , 0.69314718, 0.69314718,
       0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.        ,
       0.        , 0.        ])

In [ ]:
d1_TF_IDF = d1_TF1*IDF1
d1_TF_IDF

array([0.        , 0.        , 0.        , 0.        , 0.13862944,
       0.        , 0.06931472, 0.06931472, 0.        , 0.        ,
       0.        , 0.        ])

In [ ]:
d2_TF2 = np.array(d2_TF)
d2_TF2

array([0.1, 0.1, 0.1, 0.1, 0. , 0.2, 0. , 0. , 0.1, 0.1, 0.1, 0.1])

In [ ]:
d2_TF_IDF = d2_TF2*IDF1
d2_TF_IDF

array([0.        , 0.        , 0.        , 0.06931472, 0.        ,
       0.13862944, 0.        , 0.        , 0.06931472, 0.        ,
       0.        , 0.        ])

## 풀이

In [ ]:
# TF-IDF를 활용한 단어 벡터 직접구현

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog" 

In [ ]:
import numpy as np

In [ ]:
# document 내 토큰이 등장한 빈도수 계산
def f(t, d):
    return d.count(t)

# tf 계산
def tf(t, d):
    return f(t,d)/len(d)

# idf 계산
def idf(t, D):
    numerator = len(D)
    denominator = len([True for d in D if t in d])
    return np.log(numerator/denominator)

# tf-idf 계산
def tfidf(t, d, D):
    #print(D)
    #print(t)
    #print(d)
    #print(tf(t,d))
    #print(idf(t, D))
    #print(tf(t,d)*idf(t, D))
    #print("===")
    return tf(t,d)*idf(t, D)

# 공백을 기준으로 토큰과
def tokenizer(d):
    return d.split()

# tfidf 계산  
def tfidfScorer(D):
    docs = [tokenizer(d) for d in D]
    result = []
    for d in docs:
        result.append([(t, tfidf(t, d, docs)) for t in d])
    return result

corpus = [d1, d2]

for i, doc in enumerate(tfidfScorer(corpus)):
    print('====== document[%d] ======' % i)
    print(doc)

====== document[0] ======
[('The', 0.0), ('cat', 0.13862943611198905), ('sat', 0.0), ('on', 0.0), ('my', 0.0), ('face', 0.06931471805599453), ('I', 0.0), ('hate', 0.06931471805599453), ('a', 0.0), ('cat', 0.13862943611198905)]
====== document[1] ======
[('The', 0.0), ('dog', 0.13862943611198905), ('sat', 0.0), ('on', 0.0), ('my', 0.0), ('bed', 0.06931471805599453), ('I', 0.0), ('love', 0.06931471805599453), ('a', 0.0), ('dog', 0.13862943611198905)]


In [ ]:
# 사이킬런

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"

In [ ]:
corpus = [d1, d2]
count_vect = CountVectorizer()
countv = count_vect.fit_transform(corpus)

In [ ]:
print(countv.toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(count_vect.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 2 0 1 1 0 1 1 1 1]
 [1 0 2 0 0 1 1 1 1 1]]
{'the': 9, 'cat': 1, 'sat': 8, 'on': 7, 'my': 6, 'face': 3, 'hate': 4, 'dog': 2, 'bed': 0, 'love': 5}


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"

In [ ]:
corpus = [d1, d2]
tfidf_vect = TfidfVectorizer().fit(corpus)
tfidfv = tfidf_vect.transform(corpus)

In [ ]:
print(tfidfv.toarray())
print(tfidf_vect.vocabulary_)

[[0.         0.70600557 0.         0.35300279 0.35300279 0.
  0.25116439 0.25116439 0.25116439 0.25116439]
 [0.35300279 0.         0.70600557 0.         0.         0.35300279
  0.25116439 0.25116439 0.25116439 0.25116439]]
{'the': 9, 'cat': 1, 'sat': 8, 'on': 7, 'my': 6, 'face': 3, 'hate': 4, 'dog': 2, 'bed': 0, 'love': 5}


In [ ]:
# gensim 실습

In [ ]:
import gensim.downloader as api
from gensim.models import TfidfModel
from gensim import corpora

In [ ]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"

In [ ]:
corpus = [d1, d2]

doc_ls = [doc.split() for doc in corpus]
id2word = corpora.Dictionary(doc_ls)  # fit dictionary
corpus = [id2word.doc2bow(doc) for doc in doc_ls]  # convert corpus to BoW format

tfidf = TfidfModel(corpus)  # fit model
vector = tfidf[corpus[0]]  # apply model to the first corpus document

In [ ]:
tfidf[corpus][0]

[(3, 0.8164965809277261), (4, 0.4082482904638631), (5, 0.4082482904638631)]