<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/Sojeong_Cho/Topic%20Modeling_Latent%20Semantic%20Analysis_%EC%A1%B0%EC%86%8C%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import randomized_svd

In [2]:
docs = ['바나나 사과 포도 포도 짜장면',
        '사과 포도',
        '포도 바나나',
        '짜장면 짬뽕 탕수육',
        '볶음밥 탕수육',
        '짜장면 짬뽕',
        '라면 스시',
        '스시 짜장면',
        '가츠동 스시 소바',
        '된장찌개 김치찌개 김치',
        '김치 된장 짜장면',
        '비빔밥 김치'
          ]

## TDM

In [3]:
#토큰화

doc_ls = []

for doc in docs:
    doc_ls.append(doc.split(" "))

doc_ls

[['바나나', '사과', '포도', '포도', '짜장면'],
 ['사과', '포도'],
 ['포도', '바나나'],
 ['짜장면', '짬뽕', '탕수육'],
 ['볶음밥', '탕수육'],
 ['짜장면', '짬뽕'],
 ['라면', '스시'],
 ['스시', '짜장면'],
 ['가츠동', '스시', '소바'],
 ['된장찌개', '김치찌개', '김치'],
 ['김치', '된장', '짜장면'],
 ['비빔밥', '김치']]

In [4]:
# 각 고유 토큰에 인덱스(Index)를 지정
tokens = []
for token in doc_ls:
    for i in range(len(token)):
        tokens.append(token[i])
tokens = np.unique(tokens)
#print(tokens)

# print(list(tokens).index(tokens[0]))

doc_idx = []

for i in list(tokens):
    x = list(tokens).index(i)
    doc_idx.append(x)

#print(doc_idx)

doc_dic = {}

i = 0

for idx, token in enumerate(list(tokens)):
    doc_dic[token] = idx

#print(doc_dic)

doc_dic_1 = {doc_dic[k]:k for k in doc_dic.keys()}
doc_dic_1

{0: '가츠동',
 1: '김치',
 2: '김치찌개',
 3: '된장',
 4: '된장찌개',
 5: '라면',
 6: '바나나',
 7: '볶음밥',
 8: '비빔밥',
 9: '사과',
 10: '소바',
 11: '스시',
 12: '짜장면',
 13: '짬뽕',
 14: '탕수육',
 15: '포도'}

In [5]:
# TDM 생성

TDM = np.zeros((len(doc_ls), len(tokens)), dtype=int)

for i, doc in enumerate(doc_ls):
  for token in doc:
      TDM[i, doc_dic[token]] += 1
TDM

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
#sorted_vocab = sorted((value, key) for key, value in doc_dic.items())
#print(sorted_vocab)
#vocab = [v[1] for v in sorted_vocab]
#print(vocab)
df1 = pd.DataFrame(TDM, index=docs, columns=tokens)
df1

가츠동  김치  김치찌개  된장  된장찌개  라면  ...  소바  스시  짜장면  짬뽕  탕수육  포도
바나나 사과 포도 포도 짜장면    0   0     0   0     0   0  ...   0   0    1   0    0   2
사과 포도               0   0     0   0     0   0  ...   0   0    0   0    0   1
포도 바나나              0   0     0   0     0   0  ...   0   0    0   0    0   1
짜장면 짬뽕 탕수육          0   0     0   0     0   0  ...   0   0    1   1    1   0
볶음밥 탕수육             0   0     0   0     0   0  ...   0   0    0   0    1   0
짜장면 짬뽕              0   0     0   0     0   0  ...   0   0    1   1    0   0
라면 스시               0   0     0   0     0   1  ...   0   1    0   0    0   0
스시 짜장면              0   0     0   0     0   0  ...   0   1    1   0    0   0
가츠동 스시 소바           1   0     0   0     0   0  ...   1   1    0   0    0   0
된장찌개 김치찌개 김치        0   1     1   0     1   0  ...   0   0    0   0    0   0
김치 된장 짜장면           0   1     0   1     0   0  ...   0   0    1   0    0   0
비빔밥 김치              0   1     0   0     0   0  ...   0   0    0   0    0   0

[12 rows x 16 columns]

In [8]:
# 특이값 분해
# U = 좌특이벡터(문서-주제행렬), s = 특이값(주제 정보량), VT = 우특이벡터(주제-단어행렬) 

U, s, VT = randomized_svd(TDM,
                              n_components=4,
                              n_iter=10,
                              random_state=None)

print("U:\n {}".format(U))
print("s:\n {}".format(s))
print("VT:\n {}".format(VT))

U:
 [[ 0.79909178 -0.23631699  0.01005289  0.01866414]
 [ 0.32422891 -0.2375544   0.02301229  0.05619723]
 [ 0.32422891 -0.2375544   0.02301229  0.05619723]
 [ 0.21208198  0.48565893 -0.12813175 -0.43005064]
 [ 0.02526658  0.12189092 -0.05545517 -0.21541789]
 [ 0.18924633  0.38413621 -0.08554157 -0.26853634]
 [ 0.02364425  0.12564719 -0.32779721  0.36853889]
 [ 0.17200336  0.34344312 -0.2877235   0.18258982]
 [ 0.02646113  0.15718219 -0.46966719  0.55314475]
 [ 0.02972694  0.20690983  0.548939    0.37187387]
 [ 0.19323187  0.45209802  0.33628631  0.12275337]
 [ 0.0265624   0.16539812  0.38312378  0.24776514]]
s:
 [3.22393767 2.44629785 2.07618557 1.99908862]
VT:
 [[ 0.0082077   0.07739641  0.00922069  0.0599366   0.00922069  0.00733397
   0.34843127  0.00783718  0.00823912  0.34843127  0.0082077   0.06889362
   0.48563449  0.12448389  0.0736207   0.69686254]
 [ 0.06425309  0.33700147  0.0845808   0.18480907  0.0845808   0.05136218
  -0.19370961  0.04982669  0.06761161 -0.19370961  0.06

In [45]:
# U_1 = U[:, :4]
# # U_1

# s_1 = np.sum(s[:4])/np.sum(s)
# # s_1

# VT_1 = VT[:, :4]
# # VT_1

In [10]:
VT_matrix = VT.T
columns_name = ["Topic {}".format(i+1) for i in range(4)]
df_1 = pd.DataFrame(VT_matrix, index=tokens, columns=columns_name)
print(df_1)

word_num = 3

topic_result = []
for name in columns_name:
    topic_top = df_1[name].sort_values(ascending=False)[0:word_num]
    topic_result.append(([topic_top.index, topic_top.values]))

topic_result

       Topic 1   Topic 2   Topic 3   Topic 4
가츠동   0.008208  0.064253 -0.226216  0.276698
김치    0.077396  0.337001  0.610904  0.371365
김치찌개  0.009221  0.084581  0.264398  0.186022
된장    0.059937  0.184809  0.161973  0.061405
된장찌개  0.009221  0.084581  0.264398  0.186022
라면    0.007334  0.051362 -0.157884  0.184353
바나나   0.348431 -0.193710  0.015926  0.037448
볶음밥   0.007837  0.049827 -0.026710 -0.107758
비빔밥   0.008239  0.067612  0.184533  0.123939
사과    0.348431 -0.193710  0.015926  0.037448
소바    0.008208  0.064253 -0.226216  0.276698
스시    0.068894  0.256008 -0.522683  0.552388
짜장면   0.485634  0.584156 -0.074684 -0.187375
짬뽕    0.124484  0.355556 -0.102916 -0.349453
탕수육   0.073621  0.248355 -0.088425 -0.322881
포도    0.696863 -0.387419  0.031852  0.074895


[[Index(['포도', '짜장면', '사과'], dtype='object'),
  array([0.69686254, 0.48563449, 0.34843127])],
 [Index(['짜장면', '짬뽕', '김치'], dtype='object'),
  array([0.58415588, 0.3555557 , 0.33700147])],
 [Index(['김치', '된장찌개', '김치찌개'], dtype='object'),
  array([0.61090353, 0.26439785, 0.26439785])],
 [Index(['스시', '김치', '소바'], dtype='object'),
  array([0.55238845, 0.37136542, 0.27669846])]]

In [11]:
# 결과
result = []

for i in range(len(topic_result)):
    tmp_result = []
    for j in range(word_num):
        tmp_result.append((topic_result[i][0][j], topic_result[i][1][j]))
    result.append(tmp_result)

result

[[('포도', 0.6968625387988909),
  ('짜장면', 0.48563448882209026),
  ('사과', 0.34843126939944546)],
 [('짜장면', 0.5841558837852073),
  ('짬뽕', 0.3555556968187595),
  ('김치', 0.33700147191297813)],
 [('김치', 0.6109035277294075),
  ('된장찌개', 0.2643978491951757),
  ('김치찌개', 0.2643978491951757)],
 [('스시', 0.5523884496346675),
  ('김치', 0.37136541740506557),
  ('소바', 0.2766984641841524)]]

In [12]:
for i in range(len(result)):
    print("{} - {}".format(columns_name[i], result[i]))

Topic 1 - [('포도', 0.6968625387988909), ('짜장면', 0.48563448882209026), ('사과', 0.34843126939944546)]
Topic 2 - [('짜장면', 0.5841558837852073), ('짬뽕', 0.3555556968187595), ('김치', 0.33700147191297813)]
Topic 3 - [('김치', 0.6109035277294075), ('된장찌개', 0.2643978491951757), ('김치찌개', 0.2643978491951757)]
Topic 4 - [('스시', 0.5523884496346675), ('김치', 0.37136541740506557), ('소바', 0.2766984641841524)]


In [ ]:
# VT_result = VT_1.T
# VT_result_1 = abs(VT_result)
# print(VT_result_1)

# # b=doc_dic_1[13]
# # b
# x = VT_result_1[0]
# print("Topic 1: ", max(x))
# y = VT_result_1[1]
# print("Topic 2: ", max(y))
# z = VT_result_1[2]
# print("Topic 3: ", max(z))
# w = VT_result_1[3]
# print("Topic 4: ", max(w))

# y = VT_result[1]
# print("Topic 2: ", max(y))

# b=doc_dic_1[13]
# b

# print(doc_dic_1)