<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/quotation_kim/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [63]:
x = np.array([[0,0,1,1],[0,1,0,1]])
y = np.array([[0,1,1,0]])

In [39]:
def sigmoid(X):
	return 1 / (1 + np.exp(-X))

In [40]:
def loss(y, y_hat):
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    return loss

In [49]:
epoch = 100000
learning_rate = 0.01
for epoch in range(epoch):

    # Hidden Node
    h = sigmoid(np.dot(w1.T, x) + b1)

    # y_hat
    y_hat = sigmoid(np.dot(w2.T, h) + b2)

    # Loss 계산
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    # BackPropagate: Hidden Layer
    dw2 = np.dot(h, (y_hat - y).T)
    db2 = 1 / y.shape[1] * np.sum(y_hat - y, axis = 1, keepdims = True)
    dh  = np.dot(w2, y_hat - y)

    # BackPropagate: Input Layer
    dz1 = dh * h * (1 - h)
    dw1 = np.dot(x, dz1.T)
    db1 = 1 / y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)

    # Weight 업데이트
    w2 += -learning_rate * dw2
    b2 += -learning_rate * db2
    w1 += -learning_rate * dw1
    b1 += -learning_rate * db1

    if epoch % 100000 == 0:
        predict = y_hat
        print(predict)
        print(loss)

[[2.75398918e-04 9.95203887e-01 9.95236913e-01 6.91885295e-03]]
0.004200113539267129


In [80]:
class XOR:
    def __init__ (self, x, y):
        self.x=x
        self.y=y

    def create_weight(self,h_num):
        self.w1 = np.random.rand(2,h_num)
        self.b1 = np.random.rand(h_num,1)
        self.w2 = np.random.rand(h_num,1)
        self.b2 = np.random.rand(1,1)
    
    def optimize(self,epoch,learning_rate):
        for epoch in range(epoch):
           h = sigmoid(np.dot(self.w1.T, self.x) + self.b1)
           y_hat = sigmoid(np.dot(self.w2.T, h) + self.b2)
           loss = -1 * 1/self.x.shape[1] * np.sum(self.y * np.log(y_hat) + (1 - self.y) * np.log(1 - y_hat))
           
           dw2 = np.dot(h, (y_hat - self.y).T)
           db2 = 1 / self.y.shape[1] * np.sum(y_hat - self.y, axis = 1, keepdims = True)
           dh  = np.dot(self.w2, y_hat - self.y)
           
           dz1 = dh * h * (1 - h)
           dw1 = np.dot(self.x, dz1.T)
           db1 = 1 / self.y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)
           
           self.w2 += -learning_rate * dw2
           self.b2 += -learning_rate * db2
           self.w1 += -learning_rate * dw1
           self.b1 += -learning_rate * db1
           
           if epoch % 1000 == 0:
               predict = y_hat
               print(predict)
               print(loss)

In [81]:
xor=XOR(x,y)

In [82]:
xor.create_weight(3)

In [83]:
xor.optimize(10000,0.01)

[[0.78614402 0.81255504 0.80709686 0.82766158]]
0.9306577265831621
[[0.49851357 0.49412534 0.5118401  0.5040696 ]]
0.691551879219082
[[0.4911376  0.49191409 0.51765548 0.51000155]]
0.6892068046101536
[[0.47943841 0.48917741 0.5292544  0.51880969]]
0.6839138979678185
[[0.45890148 0.48567972 0.55235247 0.52982186]]
0.6711430819458374
[[0.42258687 0.48004404 0.59477944 0.53869235]]
0.6440823608955449
[[0.36100633 0.47245901 0.66230353 0.54110899]]
0.5971597225324807
[[0.27307257 0.47025899 0.74625004 0.53547008]]
0.5332060472070269
[[0.18475085 0.4837185  0.81558064 0.5185384 ]]
0.4663243575850624
[[0.11861183 0.53406759 0.84717899 0.4756927 ]]
0.3912526525820361
