<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/quotation_kim/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
x = np.array([[0,0,1,1],[0,1,0,1]])
y = np.array([[0,1,1,0]])

In [6]:
h_num = 3
w1 = np.random.rand(2,h_num)
b1 = np.random.rand(h_num,1)
w2 = np.random.rand(h_num,1)
b2 = np.random.rand(1,1)

In [8]:
def sigmoid(X):
	return 1 / (1 + np.exp(-X))

In [9]:
def loss(y, y_hat):
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    return loss

In [15]:
epoch = 100000
learning_rate = 0.01
for epoch in range(epoch):

    # Hidden Node
    h = sigmoid(np.dot(w1.T, x) + b1)

    # y_hat
    y_hat = sigmoid(np.dot(w2.T, h) + b2)

    # Loss 계산
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    # BackPropagate: Hidden Layer
    dw2 = np.dot(h, (y_hat - y).T)
    db2 = 1 / y.shape[1] * np.sum(y_hat - y, axis = 1, keepdims = True)
    dh  = np.dot(w2, y_hat - y)

    # BackPropagate: Input Layer
    dz1 = dh * h * (1 - h)
    dw1 = np.dot(x, dz1.T)
    db1 = 1 / y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)

    # Weight 수정
    w2 += -learning_rate * dw2
    b2 += -learning_rate * db2
    w1 += -learning_rate * dw1
    b1 += -learning_rate * db1

    if epoch % 10000 == 0:
        predict = y_hat
        print(predict)
        print(loss)

[[2.45596621e-04 9.94818049e-01 9.94838494e-01 7.49623656e-03]]
0.004535099372961817
[[2.10203300e-04 9.95367932e-01 9.95385216e-01 6.70263857e-03]]
0.004050930422678831
[[1.82826234e-04 9.95812406e-01 9.95827278e-01 6.06092995e-03]]
0.0036600135401161716
[[1.61112919e-04 9.96179104e-01 9.96192085e-01 5.53133792e-03]]
0.0033378038646458136
[[1.43532813e-04 9.96486785e-01 9.96498251e-01 5.08685426e-03]]
0.0030676687799435134
[[1.29051075e-04 9.96748625e-01 9.96758854e-01 4.70849698e-03]]
0.0028379394020569414
[[1.16945166e-04 9.96974154e-01 9.96983358e-01 4.38253609e-03]]
0.0026401885074607704
[[1.06696652e-04 9.97170431e-01 9.97178773e-01 4.09879530e-03]]
0.002468178550460953
[[9.79247415e-05 9.97342798e-01 9.97350409e-01 3.84957250e-03]]
0.002317194206021093
[[9.03439950e-05 9.97495372e-01 9.97502354e-01 3.62893114e-03]]
0.002183604931494064


### Class화 하기

In [34]:
class XOR:
    def __init__ (self, x, y):
        self.x=x
        self.y=y
        self.w1=[]
        self.b1=[]
        self.w2=[]
        self.b2=[]

    def create_weight(self,h_num):
        self.w1 = np.random.rand(2,h_num)
        self.b1 = np.random.rand(h_num,1)
        self.w2 = np.random.rand(h_num,1)
        self.b2 = np.random.rand(1,1)
    
    def optimize(self,epoch,learning_rate):
        for epoch in range(epoch):
           h = sigmoid(np.dot(self.w1.T, self.x) + self.b1)
           y_hat = sigmoid(np.dot(self.w2.T, h) + self.b2)
           loss = -1 * 1/self.x.shape[1] * np.sum(self.y * np.log(y_hat) + (1 - self.y) * np.log(1 - y_hat))

           if epoch % 10000 == 0:
               predict = y_hat
               print(predict)
               print(loss)
           
           dw2 = np.dot(h, (y_hat - self.y).T)
           db2 = 1 / self.y.shape[1] * np.sum(y_hat - self.y, axis = 1, keepdims = True)
           dh  = np.dot(self.w2, y_hat - self.y)
           
           dz1 = dh * h * (1 - h)
           dw1 = np.dot(self.x, dz1.T)
           db1 = 1 / self.y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)
           
           self.w2 += -learning_rate * dw2
           self.b2 += -learning_rate * db2
           self.w1 += -learning_rate * dw1
           self.b1 += -learning_rate * db1

In [35]:
xor=XOR(x,y)

In [36]:
xor.create_weight(3)

In [37]:
xor.optimize(100000,0.01)

[[0.84174186 0.86113774 0.86345205 0.87558224]]
1.055988946982493
[[0.04044415 0.84804152 0.855153   0.208891  ]]
0.14922621261305086
[[0.00413972 0.96440803 0.96453848 0.05079616]]
0.032156595067065044
[[0.00168255 0.98030835 0.98034383 0.02826704]]
0.017524562797231573
[[9.65768263e-04 9.86424320e-01 9.86441424e-01 1.95388894e-02]]
0.012004634281044374
[[6.47652300e-04 9.89648608e-01 9.89658954e-01 1.49214993e-02]]
0.009120508407316845
[[4.74394422e-04 9.91637273e-01 9.91644331e-01 1.20675021e-02]]
0.007351019114149632
[[3.67771914e-04 9.92985637e-01 9.92990823e-01 1.01295501e-02]]
0.006155494692910426
[[2.96597326e-04 9.93959799e-01 9.93963806e-01 8.72787956e-03]]
0.005293958429283711
[[2.46244308e-04 9.94696447e-01 9.94699658e-01 7.66704518e-03]]
0.004643742106227942
