###데이터 정의

In [82]:
import numpy as np

X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]])

### 가중치 초기화(수정전)

In [83]:
# import random
# ###매트릭스 생성
# hidden_node_number = 2

# input_layer_matrix = np.zeros((hidden_node_number,len(X))) #+1은 bias

# #hidden_layer가 하나인 인공신경망으로 가정
# hidden_layer_matrix = np.zeros((1,hidden_node_number))

# b1_matrix = np.zeros((hidden_node_number, 1))
# b2_matix = np.zeros((1, 1))

# #가중치 랜덤 값 초기화

# def matrix_init(matrix) :
#     for i in range(len(matrix)) :
#         for j in range(len(matrix[0])) :
#             matrix[i, j] = random.random()
#     return matrix

# hidden_layer_matrix = matrix_init(hidden_layer_matrix)
# input_layer_matrix = matrix_init(input_layer_matrix)
# b1_matrix = matrix_init(b1_matrix)
# b2_matrix = matrix_init(b2_matix)

In [84]:
# import pandas as pd
# #w1
# pd.DataFrame(input_layer_matrix, columns=['X{}'.format(i) for i in range(len(X))], index=['H{}'.format(j) for j in range(hidden_node_number)])

X0        X1
H0  0.858098  0.413637
H1  0.825679  0.982277

In [85]:
# #w2
# pd.DataFrame(hidden_layer_matrix, columns=['H{}'.format(j) for j in range(hidden_node_number)], index=['O'])

H0        H1
O  0.077364  0.547504

###가중치 초기화(수정후)

In [126]:
H = hidden_node_number = 3
input_layer_matrix = np.random.rand(2, H)
b1_matrix = np.random.rand(H, 1)
hidden_layer_matrix = np.random.rand(H, 1)
b2_matrix = np.random.rand(1, 1)

### feed forward

In [111]:
#hidden 노드 리스트 생성
hidden_node_list = b1_matrix + np.dot(input_layer_matrix.T, X)

#output node
output_node_list = b2_matrix + np.dot(hidden_layer_matrix.T, hidden_node_list) 



###sigmoid



In [112]:
def sigmoid(x):
    return 1 / (1 +np.exp(-x))

### hidden_node와 output_node -> sigmoid화
hidden_node_list = sigmoid(hidden_node_list)
output_node_list = sigmoid(output_node_list)



### Loss 계산

In [113]:
import math
# Y = np.array([[0, 1, 1, 0]])

loss = -1 * 1/X.shape[1] * np.sum(Y * np.log(output_node_list)+ (1 - Y) * np.log(1 - output_node_list))
loss

1.050523743339257

###기울기 계산

In [114]:
cost = output_node_list - Y


gradient_w2 = np.dot(hidden_node_list, cost.T) #기본적으로 열벡터
print("gradient_w2 : {}".format(gradient_w2))

gradient_b2 = 1. / Y.shape[1] * np.sum(cost, axis = 1, keepdims = True)
print("gradient_b2 : {}".format(gradient_b2))

gradient_h = np.dot(hidden_layer_matrix, cost)
print("gradient_h : {}".format(gradient_h))

z1 = gradient_h * hidden_node_list * (1 - np.array(hidden_node_list))
gradient_w1 = np.dot(X, z1.T)
print("gradient_w1 : {}".format(gradient_w1))

gradient_b1 = 1./Y.shape[1] * np.sum(z1, axis = 1, keepdims = True)
print("gradient_b1 : {}".format(gradient_b1))


gradient_w2 : [[1.11525998]
 [0.9233564 ]
 [0.87144053]]
gradient_b2 : [[0.34876071]]
gradient_h : [[ 0.63858401 -0.11345522 -0.12528774  0.74331371]
 [ 0.03581282 -0.00636275 -0.00702634  0.04168622]
 [ 0.4554851  -0.08092461 -0.08936444  0.53018603]]
gradient_w1 : [[0.06495039 0.00696541 0.09650745]
 [0.06923085 0.00726449 0.09788981]]
gradient_b1 : [[0.04405921]
 [0.00354099]
 [0.0471978 ]]


###가중치 학습

In [115]:
leaning_rate = 0.1

In [116]:
input_layer_matrix -= leaning_rate * gradient_w1
print("input_layer_matrix : {}".format(input_layer_matrix)) 

hidden_layer_matrix -= leaning_rate * gradient_w2 
print("hidden_layer_matrix : {}".format(hidden_layer_matrix)) 

b1_matrix -= leaning_rate * gradient_b1 
print("b1_matrix : {}".format(b1_matrix)) 

b2_matix -= leaning_rate * gradient_b2
print("b2_matrix : {}".format(b2_matrix))

# hidden_node_list -= leaning_rate * gradient_h
# print("hidden_node_list : {}".format(hidden_node_list))


input_layer_matrix : [[0.34432994 0.06845777 0.26387546]
 [0.55577707 0.38564422 0.14039831]]
hidden_layer_matrix : [[ 0.7079146 ]
 [-0.0463801 ]
 [ 0.49734128]]
b1_matrix : [[0.95323582]
 [0.43017117]
 [0.28057513]]
b2_matrix : [[0.29028259]]


In [117]:
output_node_list

array([[0.77929261, 0.86154552, 0.84710576, 0.90709895]])

###함수화를 통한 반복

In [197]:
class XOR() :
    def __init__(self, X, Y, h) :
        import numpy as np
        self.X = X
        self.Y = Y
        self.hidden_node_number = h


    def _init_weights(self) :
        import random
        ###매트릭스 생성

        H = self.hidden_node_number
        input_layer_matrix = np.random.rand(2, H)
        b1_matrix = np.random.rand(H, 1)
        hidden_layer_matrix = np.random.rand(H, 1)
        b2_matrix = np.random.rand(1, 1)

        return input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix
        
    def sigmoid(self, x):
        return 1 / (1 +np.exp(-x))

    def _feedfoward(self,input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix) :
        
        #hidden_node
        hidden_node_list = b1_matrix + np.dot(input_layer_matrix.T, self.X)
        hidden_node_list = self.sigmoid(hidden_node_list)

        #output node
        output_node_list = self.sigmoid(b2_matrix + np.dot(hidden_layer_matrix.T, hidden_node_list))
        output_node_list = self.sigmoid(output_node_list)
        
        return hidden_node_list, output_node_list

    def _eval_loss (self, output_node_list):
        import math
        loss = -1 * 1/self.X.shape[1] * np.sum(self.Y * np.log(output_node_list)+ (1 - self.Y) * np.log(1 - output_node_list))
        return loss

    def _gradients (self, input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix, output_node_list, hidden_node_list, leaning_rate = 0.1):
        
        leaning_rate = leaning_rate
        cost = output_node_list - self.Y

        gradient_w2 = np.dot(hidden_node_list, cost.T) 
        
        gradient_b2 = 1. / self.Y.shape[1] * np.sum(cost, axis = 1, keepdims= True)
        
        gradient_h = np.dot(hidden_layer_matrix, cost)

        z1 = gradient_h * hidden_node_list * (1 - np.array(hidden_node_list))
       
        gradient_w1 = np.dot(self.X, z1.T)
        
        gradient_b1 = 1./self.Y.shape[1] * np.sum(z1, axis = 1, keepdims= True)
                
        #가중치 학습
        
        input_layer_matrix += -leaning_rate * gradient_w1 # w1 업데이트

        hidden_layer_matrix += -leaning_rate * gradient_w2 # w2 업데이트

        b1_matrix += -leaning_rate * gradient_b1 # b1 업데이트

        b2_matrix += -leaning_rate * gradient_b2 # b2 업데이트

        return input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix


    ##########이건 왜 안되는 건지 질문하기.. 함수로 로컬 변수에 리턴받고 바로 매개변수로 쓸 수 없는지 - 가중치 학습이 안됨. 


    # def optimize (self, learning_rate = 0.1, epoch = 2000) :
        
    #     input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix = test._init_weights() #w1, w2, b1, b2 가중치 초기화

    #     for count in range(epoch) :
    #         #hidden_node와 Y_hat 계산 후 sigmoid화
    #         hidden_node_list, output_node_list = self._feedfoward(input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix)

    #         #w1, w2, b1, b2 가중치 학습 
    #         input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix = self._gradients(input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix, output_node_list, hidden_node_list)
            
    #         if count%5000 == 0 :
    #             print("gradient_w2 : {}".format(gradient_w2))
    #             print("gradient_b2 : {}".format(gradient_b2))
    #             print("gradient_w1 : {}".format(gradient_w1))
    #             print("gradient_b1 : {}".format(gradient_b1))
    #             print("\n**********************\n")
    #             print(self._eval_loss(output_node_list))
    #     return output_node_list.round(3)

    def optimize (self, learning_rate = 0.1, epoch = 2000) :
        
        input_layer_matrix, hidden_layer_matrix, b1_matrix, b2_matrix = self._init_weights() #w1, w2, b1, b2 가중치 초기화

        for count in range(epoch) :
            #hidden_node와 Y_hat 계산 후 sigmoid화
            hidden_node_list = b1_matrix + np.dot(input_layer_matrix.T, self.X)
            hidden_node_list = self.sigmoid(hidden_node_list)

            output_node_list = self.sigmoid(b2_matrix + np.dot(hidden_layer_matrix.T, hidden_node_list))
            output_node_list = self.sigmoid(output_node_list)

            #w1, w2, b1, b2 가중치 학습 
            a = leaning_rate

            cost = output_node_list - self.Y

            gradient_w2 = np.dot(hidden_node_list, cost.T) 
            
            gradient_b2 = 1. / self.Y.shape[1] * np.sum(cost, axis = 1, keepdims= True)
            
            gradient_h = np.dot(hidden_layer_matrix, cost)

            z1 = gradient_h * hidden_node_list * (1 - np.array(hidden_node_list))
        
            gradient_w1 = np.dot(self.X, z1.T)
            
            gradient_b1 = 1./self.Y.shape[1] * np.sum(z1, axis = 1, keepdims= True)
                    
            #가중치 학습
            
            input_layer_matrix -= a * gradient_w1 # w1 업데이트

            hidden_layer_matrix -= a * gradient_w2 # w2 업데이트

            b1_matrix -= a * gradient_b1 # b1 업데이트

            b2_matrix -= a * gradient_b2 # b2 업데이트

            if count%1000 == 0 :
                print("gradient_w2 : {}".format(gradient_w2))
                print("gradient_b2 : {}".format(gradient_b2))
                print("gradient_w1 : {}".format(gradient_w1))
                print("gradient_b1 : {}".format(gradient_b1))
                print("\n**********************\n")
                print("loss : {}".format(self._eval_loss(output_node_list)))
                print(output_node_list.round(0))
                print("\n**********************\n")

        return output_node_list.round(3)


In [198]:
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]])

In [199]:
test = XOR(X, Y, 2)

predicts = test.optimize(0.05, 5000)
print("Y hat : {}".format(predicts))
print("predicts : {}".format([1 if y > 0.5 else 0 for y in predicts[0]]))

#로스가 증가하는 이유 ? -> 가중치 학습이 잘 안 이루어짐.. 왜?

gradient_w2 : [[0.45806067]
 [0.4716133 ]]
gradient_b2 : [[0.18388781]]
gradient_w1 : [[0.03347489 0.04490544]
 [0.02841539 0.04086239]]
gradient_b1 : [[0.02102278]
 [0.02418018]]

**********************

loss : 0.765550574652975
[[1. 1. 1. 1.]]

**********************

gradient_w2 : [[0.4779873]
 [0.4819155]]
gradient_b2 : [[0.00931038]]
gradient_w1 : [[-0.0786753  -0.07249916]
 [ 0.08107562  0.07401276]]
gradient_b1 : [[-0.04129625]
 [-0.03750958]]

**********************

loss : 0.6751872756634241
[[0. 1. 0. 0.]]

**********************

gradient_w2 : [[0.49768119]
 [0.49783596]]
gradient_b2 : [[0.00666218]]
gradient_w1 : [[-0.02761194 -0.02669682]
 [ 0.02776248  0.02683027]]
gradient_b1 : [[-0.01379902]
 [-0.0133277 ]]

**********************

loss : 0.6801657619244598
[[0. 1. 0. 0.]]

**********************

gradient_w2 : [[0.49918715]
 [0.49921999]]
gradient_b2 : [[0.00443007]]
gradient_w1 : [[-0.01648121 -0.01614936]
 [ 0.0165066   0.0161721 ]]
gradient_b1 : [[-0.00819262]
 [-0.