<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-statisticsmodel/blob/master/%20Sojeong_Cho/Topic%20Modeling_Latent%20Semantic%20Analysis_%EC%A1%B0%EC%86%8C%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
docs = ['바나나 사과 포도 포도 짜장면',
        '사과 포도',
        '포도 바나나',
        '짜장면 짬뽕 탕수육',
        '볶음밥 탕수육',
        '짜장면 짬뽕',
        '라면 스시',
        '스시 짜장면',
        '가츠동 스시 소바',
        '된장찌개 김치찌개 김치',
        '김치 된장 짜장면',
        '비빔밥 김치'
          ]

## TDM

In [3]:
#토큰화

doc_ls = []

for doc in docs:
    doc_ls.append(doc.split(" "))

doc_ls

[['바나나', '사과', '포도', '포도', '짜장면'],
 ['사과', '포도'],
 ['포도', '바나나'],
 ['짜장면', '짬뽕', '탕수육'],
 ['볶음밥', '탕수육'],
 ['짜장면', '짬뽕'],
 ['라면', '스시'],
 ['스시', '짜장면'],
 ['가츠동', '스시', '소바'],
 ['된장찌개', '김치찌개', '김치'],
 ['김치', '된장', '짜장면'],
 ['비빔밥', '김치']]

In [16]:
# 각 고유 토큰에 인덱스(Index)를 지정
tokens = []
for token in doc_ls:
    for i in range(len(token)):
        tokens.append(token[i])
tokens = np.unique(tokens)
#print(tokens)

# print(list(tokens).index(tokens[0]))

doc_idx = []

for i in list(tokens):
    x = list(tokens).index(i)
    doc_idx.append(x)

#print(doc_idx)

doc_dic = {}

i = 0

for idx, token in enumerate(list(tokens)):
    doc_dic[token] = idx

#print(doc_dic)

doc_dic_1 = {doc_dic[k]:k for k in doc_dic.keys()}
doc_dic_1

{0: '가츠동',
 1: '김치',
 2: '김치찌개',
 3: '된장',
 4: '된장찌개',
 5: '라면',
 6: '바나나',
 7: '볶음밥',
 8: '비빔밥',
 9: '사과',
 10: '소바',
 11: '스시',
 12: '짜장면',
 13: '짬뽕',
 14: '탕수육',
 15: '포도'}

In [17]:
# TDM 생성

TDM = np.zeros((len(doc_ls), len(tokens)), dtype=int)

for i, doc in enumerate(doc_ls):
  for token in doc:
      TDM[i, doc_dic[token]] += 1
TDM

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
#sorted_vocab = sorted((value, key) for key, value in doc_dic.items())
#print(sorted_vocab)
#vocab = [v[1] for v in sorted_vocab]
#print(vocab)
df1 = pd.DataFrame(TDM, index=docs, columns=tokens)
df1

가츠동  김치  김치찌개  된장  된장찌개  라면  ...  소바  스시  짜장면  짬뽕  탕수육  포도
바나나 사과 포도 포도 짜장면    0   0     0   0     0   0  ...   0   0    1   0    0   2
사과 포도               0   0     0   0     0   0  ...   0   0    0   0    0   1
포도 바나나              0   0     0   0     0   0  ...   0   0    0   0    0   1
짜장면 짬뽕 탕수육          0   0     0   0     0   0  ...   0   0    1   1    1   0
볶음밥 탕수육             0   0     0   0     0   0  ...   0   0    0   0    1   0
짜장면 짬뽕              0   0     0   0     0   0  ...   0   0    1   1    0   0
라면 스시               0   0     0   0     0   1  ...   0   1    0   0    0   0
스시 짜장면              0   0     0   0     0   0  ...   0   1    1   0    0   0
가츠동 스시 소바           1   0     0   0     0   0  ...   1   1    0   0    0   0
된장찌개 김치찌개 김치        0   1     1   0     1   0  ...   0   0    0   0    0   0
김치 된장 짜장면           0   1     0   1     0   0  ...   0   0    1   0    0   0
비빔밥 김치              0   1     0   0     0   0  ...   0   0    0   0    0   0

[12 rows x 16 columns]

In [46]:
# 특이값 분해
# U = 좌특이벡터(문서-주제행렬), s = 특이값(주제 정보량), VT = 우특이벡터(주제-단어행렬) 

U, s, VT = np.linalg.svd(df1)
print("U:\n {}".format(U))
print("s:\n {}".format(s))
print("VT:\n {}".format(VT))

U:
 [[ 7.99091783e-01  2.36316994e-01 -1.00528910e-02  1.86641353e-02
   2.26958130e-02 -1.49376350e-03 -2.77279457e-03 -3.68544915e-02
   1.19639008e-16 -1.17652823e-01 -2.96599016e-02  5.37170383e-01]
 [ 3.24228913e-01  2.37554400e-01 -2.30122874e-02  5.61972271e-02
  -9.68984211e-02  3.15314058e-03  5.42121261e-03  5.97770914e-02
  -7.07106781e-01  1.44987002e-01  3.17878330e-02 -5.47468895e-01]
 [ 3.24228913e-01  2.37554400e-01 -2.30122874e-02  5.61972271e-02
  -9.68984211e-02  3.15314058e-03  5.42121261e-03  5.97770914e-02
   7.07106781e-01  1.44987002e-01  3.17878330e-02 -5.47468895e-01]
 [ 2.12081980e-01 -4.85658930e-01  1.28131746e-01 -4.30050644e-01
  -2.29550714e-01 -1.49219512e-01  7.74475499e-02  2.17717819e-01
  -3.74700271e-16  1.91835325e-01  5.93643666e-01  1.49190202e-02]
 [ 2.52665818e-02 -1.21890924e-01  5.54551687e-02 -2.15417887e-01
  -7.72035525e-01  3.54259781e-01 -1.44920552e-01 -2.56260382e-01
  -2.77555756e-17 -1.33737715e-01 -3.29953280e-01 -7.67610447e-03]
 

In [45]:
# U_1 = U[:, :4]
# # U_1

# s_1 = np.sum(s[:4])/np.sum(s)
# # s_1

# VT_1 = VT[:, :4]
# # VT_1

In [47]:
k = 4

VT_matrix = VT.T[:, :k]
columns_name = ["Topic {}".format(i+1) for i in range(k)]
df_1 = pd.DataFrame(VT_matrix, index=tokens, columns=columns_name)
print(df_1)

word_num = 3

topic_result = []
for name in columns_name:
    topic_top = df_1[name].sort_values(ascending=False)[0:word_num]
    topic_result.append(([topic_top.index, topic_top.values]))

topic_result

       Topic 1   Topic 2   Topic 3   Topic 4
가츠동   0.008208 -0.064253  0.226216  0.276698
김치    0.077396 -0.337001 -0.610904  0.371365
김치찌개  0.009221 -0.084581 -0.264398  0.186022
된장    0.059937 -0.184809 -0.161973  0.061405
된장찌개  0.009221 -0.084581 -0.264398  0.186022
라면    0.007334 -0.051362  0.157884  0.184353
바나나   0.348431  0.193710 -0.015926  0.037448
볶음밥   0.007837 -0.049827  0.026710 -0.107758
비빔밥   0.008239 -0.067612 -0.184533  0.123939
사과    0.348431  0.193710 -0.015926  0.037448
소바    0.008208 -0.064253  0.226216  0.276698
스시    0.068894 -0.256008  0.522683  0.552388
짜장면   0.485634 -0.584156  0.074684 -0.187375
짬뽕    0.124484 -0.355556  0.102916 -0.349453
탕수육   0.073621 -0.248355  0.088425 -0.322881
포도    0.696863  0.387419 -0.031852  0.074895


[[Index(['포도', '짜장면', '사과'], dtype='object'),
  array([0.69686254, 0.48563449, 0.34843127])],
 [Index(['포도', '사과', '바나나'], dtype='object'),
  array([0.38741921, 0.19370961, 0.19370961])],
 [Index(['스시', '소바', '가츠동'], dtype='object'),
  array([0.52268348, 0.22621639, 0.22621639])],
 [Index(['스시', '김치', '소바'], dtype='object'),
  array([0.55238845, 0.37136542, 0.27669846])]]

In [48]:
# 결과
result = []

for i in range(len(topic_result)):
    tmp_result = []
    for j in range(word_num):
        tmp_result.append((topic_result[i][0][j], topic_result[i][1][j]))
    result.append(tmp_result)

result

[[('포도', 0.6968625387988909),
  ('짜장면', 0.4856344888220902),
  ('사과', 0.34843126939944546)],
 [('포도', 0.38741921296736714),
  ('사과', 0.1937096064836836),
  ('바나나', 0.1937096064836836)],
 [('스시', 0.5226834790874777),
  ('소바', 0.22621638508820763),
  ('가츠동', 0.22621638508820757)],
 [('스시', 0.5523884496346748),
  ('김치', 0.371365417405056),
  ('소바', 0.2766984641841555)]]

In [49]:
for i in range(len(result)):
    print("{} - {}".format(columns_name[i], result[i]))

Topic 1 - [('포도', 0.6968625387988909), ('짜장면', 0.4856344888220902), ('사과', 0.34843126939944546)]
Topic 2 - [('포도', 0.38741921296736714), ('사과', 0.1937096064836836), ('바나나', 0.1937096064836836)]
Topic 3 - [('스시', 0.5226834790874777), ('소바', 0.22621638508820763), ('가츠동', 0.22621638508820757)]
Topic 4 - [('스시', 0.5523884496346748), ('김치', 0.371365417405056), ('소바', 0.2766984641841555)]


In [ ]:
# VT_result = VT_1.T
# VT_result_1 = abs(VT_result)
# print(VT_result_1)

# # b=doc_dic_1[13]
# # b
# x = VT_result_1[0]
# print("Topic 1: ", max(x))
# y = VT_result_1[1]
# print("Topic 2: ", max(y))
# z = VT_result_1[2]
# print("Topic 3: ", max(z))
# w = VT_result_1[3]
# print("Topic 4: ", max(w))

# y = VT_result[1]
# print("Topic 2: ", max(y))

# b=doc_dic_1[13]
# b

# print(doc_dic_1)